/*
Without deadlock, the program should print a series of "Setting data" and Data = ??
However, from the program, we actually get "exiting" as well
Also, the data generated by set_data(), is some random number.

Example output:

Setting data	Data = 1804289383
Setting data	Setting data	Data = 1681692777
Setting data	Data = 1714636915
Data = 1714636915
Setting data	Data = 1957747793
exiting

*/


#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>

pthread_mutex_t mutexl = PTHREAD_MUTEX_INITIALIZER;

int global_data = 0;

void read_data();
void set_data();

int main(void)
{
    pthread_t thread1, thread2;
    int thread_return1, thread_return2;
    int i;

    for (i = 0; i < 5; i++)
    {
        thread_return1 = pthread_create(&thread1, NULL, (void *)&set_data, NULL);
        thread_return2 = pthread_create(&thread2, NULL, (void *)&read_data, NULL);
    }

    // wait until two threads complete
    pthread_join(thread1, NULL);
    pthread_join(thread2, NULL);

    printf("exiting\n");
    exit(0);

}

void set_data()
{
    pthread_mutex_lock(&mutexl); // lock the critical section
    printf("Setting data\t");
    global_data = rand();
    pthread_mutex_unlock(&mutexl); // unlock the critical section, allow other thread to access the protected data
}

void read_data()
{
    int data;

    // protect the critical section
    pthread_mutex_lock(&mutexl);
    data = global_data;
    printf("Data = %d\n", data);
    pthread_mutex_unlock(&mutexl);
}
